#!/usr/bin/python

import os
import sys

def run():
    import urls
    if os.environ.get("REQUEST_METHOD", ""):
        from wsgiref.handlers import BaseCGIHandler
        BaseCGIHandler(sys.stdin, sys.stdout, sys.stderr, os.environ).run(urls.urls)
    else:
        from wsgiref.simple_server import WSGIServer, WSGIRequestHandler
        httpd = WSGIServer(('', 8080), WSGIRequestHandler)
        httpd.set_app(urls.urls)
        print "Serving HTTP on %s port %s ..." % httpd.socket.getsockname()
        httpd.serve_forever()

def help():
    print "Available commands:"
    print "  run  - launch the server"
    print "  help - print this and exist"
    print

if __name__ == "__main__":
    if len(sys.argv) == 1:
        help()
        sys.exit(0)
    if sys.argv[1] == "run":
        try:
            run()
        except KeyboardInterrupt:
            print "end"
    elif sys.argv[1] == "help":
        help()
