#!/usr/bin/python

import os
import sys
from os.path import abspath, curdir
from urllib import urlopen
from os.path import exists

import db

def run():
    import urls
    if os.environ.get("REQUEST_METHOD", ""):
        from wsgiref.handlers import BaseCGIHandler
        BaseCGIHandler(sys.stdin, sys.stdout, sys.stderr, os.environ).run(urls.urls)
    else:
        from wsgiref.simple_server import WSGIServer, WSGIRequestHandler
        httpd = WSGIServer(('', 8080), WSGIRequestHandler)
        httpd.set_app(urls.urls)
        print "Serving HTTP on %s port %s ..." % httpd.socket.getsockname()
        httpd.serve_forever()

def help():
    print "Available commands:"
    print "  run  - launch the server"
    print "  add  - add a list of ebooks to the db"
    print "  help - print this and exist"
    print

def add_book(*books):
    if not books:
        print "give me at least one ebook name"
        sys.exit(1)
    for book in books:
        book_path = abspath(curdir) + "/" + book
        if not exists(book_path):
            print "Error: '%s' doesn't not exists" % book_path
            return
        db.add_a_book(book_path, book)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        help()
        sys.exit(0)
    if sys.argv[1] == "run":
        try:
            run()
        except KeyboardInterrupt:
            print "end"
    elif sys.argv[1] == "help":
        help()
    elif sys.argv[1] == "add":
        add_book(*sys.argv[2:])
    else:
        print "Error: invalid command '%s'" % sys.argv[1]
        print
        help()
        sys.exit(1)
